site_name: WriteBase
site_url: https://doc.writebase.app
docs_dir: docs

theme:
  name: material
  palette:
    scheme: default
    primary: indigo
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - toc.follow

markdown_extensions:
  - toc:
      toc_depth: 4
      title: On this page
      toc_class: toc
      anchorlink: true
      permalink: true
      baselevel: 1

nav:
  - Home: index.md
  - Why WriteBase: why-writebase.md
  - Markdown Test: markdown-test.md
  - Waiting List: waiting-list---information.md
