title: WriteBase
description: Documentation for WriteBase
remote_theme: just-the-docs/just-the-docs

color_scheme: light

aux_links:
  "Substack": "https://thomaslarsson.substack.com"

# Table of Contents på höger sida
toc:
  enabled: true
  min_level: 2
  max_level: 4
